### ISSUE TITLE
how to convert SMAC-M output to OSM (tile)

### ISSUE THREAD

**Issue by teriterance** [LarsSchy/SMAC-M#27]
hello, 
Hello to you, I would like if it is possible to convert the output of SMAC-M into a tile compatible with Open Street Map. In order to display the maps (S57, CM93) in a web browser. 

As far as I know, it is possible to convert the shape files to an Open Street Map compatible format.

I'm new in the GIS world, I have to do this for an internship.

**Comment by smercier** [comment]
Hi teriterance

No need to convert to shapefiles.  It's relatively simple soon you install properly this repo and make it run with your S57 raw data(properly converted w/ this tool).  Because you will have a WMS of your EMC data up and running, you can easily install Mapcache(https://mapserver.org/mapcache/) to publish tiles on the top of the OpenStreetMap base map.  It's what we do for our needs.

simon

**Comment by teriterance** [comment]
Yes thank you, I took some time to learn about mapcache; and try to understand it.
I have 2 questions
- the information is added above that of OSM, how to do so that they do not conflict with mine, my basic objective being to modify the basemap
- How to add information on a tile without creating it yourself.

Gabin

**Comment by smercier** [comment]
your SMAC-M WMS will be simply placed on the top of OSM and you can hide area layers of your S57 dataset in smac configuration file!  Are you familiar with GIS? With OpenLayers ?

**Comment by teriterance** [comment]
@smercier I am new to this field, I just have the theoretical basics from my lecture of  Mapserver, OSM and Mapcache documentation.
